import React from "react";
import { Audio } from "@remotion/media";
import { staticFile, Sequence, useVideoConfig, interpolate, spring, useCurrentFrame } from "remotion";
import { DeviceMockup } from "./components/DeviceMockup";
import { TextOverlay } from "./components/TextOverlay";
import { FeatureBadge } from "./components/FeatureBadge";

export interface PromoProps {
  audioSrc: string;
}

export const ProductPromoComposition: React.FC<PromoProps> = ({ audioSrc }) => {
  const { durationInFrames, fps } = useVideoConfig();

  // Divide into 4 scene blocks:
  // Scene 1: 0 to 135 (~4.5s)
  // Scene 2: 135 to 270 (~4.5s)
  // Scene 3: 270 to 405 (~4.5s)
  // Scene 4: 405 to durationInFrames (Outro & CTA)
  const scene1Duration = 135;
  const scene2Duration = 135;
  const scene3Duration = 135;
  const scene4Duration = durationInFrames - 405;

  return (
    <div
      style={{
        flex: 1,
        width: "100%",
        height: "100%",
        backgroundColor: "#030712",
        backgroundImage: `
          radial-gradient(ellipse at 50% 0%, #1e1b4b 0%, #030712 70%),
          radial-gradient(circle at 10% 90%, rgba(99, 102, 241, 0.15) 0%, transparent 40%),
          radial-gradient(circle at 90% 90%, rgba(56, 189, 248, 0.12) 0%, transparent 40%)
        `,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
        overflow: "hidden",
      }}
    >
      {/* Background Animated Ambient Lights */}
      <BackgroundAmbientGlow />

      {/* 1. Synchronized Voiceover Audio generated by Gemini */}
      <Audio src={staticFile(audioSrc)} />

      {/* 2. Scene 1: Introduction & Executive Dashboard */}
      <Sequence from={0} durationInFrames={scene1Duration}>
        <TextOverlay
          category="Tailored Boutique SaaS"
          headline="Meet Alangkart ERP:"
          highlightText="The Rental OS"
          subtitle="Automate luxury garment rentals, custom tailoring, and deposit tracking"
        />
        <div style={{ position: "relative" }}>
          <DeviceMockup
            imageSrc="dashboard.png"
            urlLabel="app.alangkart.com/analytics-overview"
          />
          <FeatureBadge
            icon="📊"
            title="Real-time Financials"
            subtitle="Ledger-grade deposit & revenue tracking"
            position="right"
            top={120}
            delay={20}
          />
          <FeatureBadge
            icon="👗"
            title="Garment SOP"
            subtitle="Rental, Alteration & Return tracking"
            position="left"
            top={280}
            delay={35}
          />
        </div>
      </Sequence>

      {/* 3. Scene 2: Inventory Availability Matrix & Conflict Prevention */}
      <Sequence from={scene1Duration} durationInFrames={scene2Duration}>
        <TextOverlay
          category="Inventory Intelligence"
          headline="Real-Time Garment"
          highlightText="Availability Matrix"
          subtitle="Interactive calendar stops double-bookings before they happen"
        />
        <div style={{ position: "relative" }}>
          <DeviceMockup
            imageSrc="inventory.png"
            urlLabel="app.alangkart.com/inventory/availability"
          />
          <FeatureBadge
            icon="📅"
            title="Conflict Detection"
            subtitle="Automatic date collision lockouts"
            position="right"
            top={140}
            delay={15}
          />
          <FeatureBadge
            icon="🏷️"
            title="SKU & Barcode Matrix"
            subtitle="Scan to instantly view garment status"
            position="left"
            top={300}
            delay={30}
          />
        </div>
      </Sequence>

      {/* 4. Scene 3: Automated WhatsApp Billing & Barcode Workflow */}
      <Sequence from={scene1Duration + scene2Duration} durationInFrames={scene3Duration}>
        <TextOverlay
          category="Frictionless Dispatch"
          headline="Automated WhatsApp"
          highlightText="Billing & Invoicing"
          subtitle="Dispatch tax invoices, rental contracts, and pickup receipts via WhatsApp"
        />
        <div style={{ position: "relative" }}>
          <DeviceMockup
            imageSrc="whatsapp_billing.png"
            urlLabel="app.alangkart.com/orders/dispatch-bill"
          />
          <FeatureBadge
            icon="💬"
            title="1-Click WhatsApp Send"
            subtitle="Instant PDF delivery to client phones"
            position="right"
            top={130}
            delay={15}
          />
          <FeatureBadge
            icon="🔐"
            title="Deposit Escrow"
            subtitle="Auto-calculated refunds upon return"
            position="left"
            top={290}
            delay={30}
          />
        </div>
      </Sequence>

      {/* 5. Scene 4: Mobile Experience & High-Converting CTA */}
      <Sequence
        from={scene1Duration + scene2Duration + scene3Duration}
        durationInFrames={scene4Duration}
      >
        <TextOverlay
          category="Grow Your Boutique"
          headline="Double Your Capacity with"
          highlightText="Zero Chaos"
          subtitle="Experience the all-in-one ERP built specifically for bridal and luxury rentals"
        />
        <div style={{ display: "flex", alignItems: "center", gap: 50, marginTop: 10 }}>
          <div style={{ position: "relative" }}>
            <DeviceMockup
              imageSrc="mobile.png"
              urlLabel="app.alangkart.com/mobile-orders"
              zoomScale={1.03}
            />
          </div>
          <CallToActionBox />
        </div>
      </Sequence>
    </div>
  );
};

// Subtle ambient particle/light background effect
const BackgroundAmbientGlow: React.FC = () => {
  const frame = useCurrentFrame();
  const shiftX = Math.sin(frame / 35) * 40;
  const shiftY = Math.cos(frame / 30) * 30;

  return (
    <div
      style={{
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        pointerEvents: "none",
        zIndex: 0,
        overflow: "hidden",
      }}
    >
      <div
        style={{
          position: "absolute",
          top: "15%",
          left: `calc(50% + ${shiftX}px)`,
          transform: "translateX(-50%)",
          width: 800,
          height: 400,
          background: "radial-gradient(ellipse, rgba(99, 102, 241, 0.18) 0%, transparent 70%)",
          filter: "blur(60px)",
        }}
      />
      <div
        style={{
          position: "absolute",
          bottom: "10%",
          right: `calc(15% + ${shiftY}px)`,
          width: 500,
          height: 350,
          background: "radial-gradient(circle, rgba(56, 189, 248, 0.12) 0%, transparent 70%)",
          filter: "blur(50px)",
        }}
      />
    </div>
  );
};

// Conversion CTA Card for Outro
const CallToActionBox: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const pop = spring({
    frame,
    fps,
    config: { damping: 14, stiffness: 100 },
  });

  return (
    <div
      style={{
        transform: `scale(${pop})`,
        background: "linear-gradient(135deg, rgba(30, 27, 75, 0.9) 0%, rgba(15, 23, 42, 0.95) 100%)",
        border: "1px solid rgba(129, 140, 248, 0.4)",
        borderRadius: 24,
        padding: "36px 40px",
        boxShadow: "0 20px 50px rgba(0, 0, 0, 0.7), 0 0 40px rgba(99, 102, 241, 0.3)",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        maxWidth: 420,
        zIndex: 10,
      }}
    >
      <div
        style={{
          width: 64,
          height: 64,
          borderRadius: 18,
          background: "linear-gradient(135deg, #6366f1 0%, #38bdf8 100%)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontSize: 32,
          marginBottom: 16,
          boxShadow: "0 10px 25px rgba(99,102,241,0.5)",
        }}
      >
        ✨
      </div>
      <h3
        style={{
          color: "#ffffff",
          fontSize: 26,
          fontWeight: 800,
          fontFamily: "system-ui, -apple-system, sans-serif",
          margin: 0,
          textAlign: "center",
        }}
      >
        Ready to Modernize Your Boutique?
      </h3>
      <p
        style={{
          color: "#94a3b8",
          fontSize: 15,
          marginTop: 10,
          marginBottom: 24,
          textAlign: "center",
          fontFamily: "system-ui, -apple-system, sans-serif",
        }}
      >
        Join 100+ high-end studios managing rentals with 100% confidence.
      </p>

      <div
        style={{
          padding: "16px 36px",
          borderRadius: 999,
          background: "linear-gradient(90deg, #6366f1 0%, #38bdf8 100%)",
          color: "#ffffff",
          fontSize: 18,
          fontWeight: 800,
          fontFamily: "system-ui, -apple-system, sans-serif",
          boxShadow: "0 10px 30px rgba(99, 102, 241, 0.4)",
          display: "flex",
          alignItems: "center",
          gap: 10,
        }}
      >
        <span>Get Started Today</span>
        <span>→</span>
      </div>

      <div
        style={{
          color: "#64748b",
          fontSize: 13,
          marginTop: 14,
          fontFamily: "system-ui, -apple-system, sans-serif",
        }}
      >
        No Credit Card Required • Instant Setup
      </div>
    </div>
  );
};
